All file structure is correct pre ejection
Everything is as it should be pre-ejection. Getting Uncaught SyntaxError: Unexpected token '<' (at webWorker.js:1:1) error that needs to be fixed by tweaking webpacker.